### PR TITLE
Allow detecting image sizes for absolute paths

### PR DESCRIPTION
**Pull request by tdhooper**

### CODE REVIEW

**Comment by simonsmith** [comment]
@tdhooper Does this currently work as expected for you? I think `image-size` expects at least a partial download of the image before it can detect the size.

**Comment by tdhooper** [comment]
Yes, with this change, I can do:

    background: url(/static/images/some_image.png);

And use the `resolveImagePath` option to point it to the right place on the filesystem.

**Comment by simonsmith** [comment]
Ah of course. Sorry I thought this was related to remote URLs.

@niksy Any reason why this check was added initially?

**Comment by niksy** [comment]
@simonsmith I think it was related to URLs as you mentioned. It definitely should skip if it’s URL-like string which is checked by `isUrl` (although image-size has [remote URL option](https://github.com/image-size/image-size#using-a-url), but I think we should skip that and only focus on local assets), but absolute paths can be allowed since that is what’s passed to image-size and it’s handled by that module. So I think this change should be OK.

**Comment by simonsmith** [comment]
@niksy Great, thanks for that. I'll merge and add a test and then release a new version.

Cheers @tdhooper

**Comment by tdhooper** [comment]
Thank you 👍

**Pull request merged**
