### PR TITLE
Add support for PostCSS 8

### PR DESCRIPTION
**Pull request by niksy**
Following [official plugin migration guide](https://evilmartians.com/chronicles/postcss-8-plugin-migration), I’ve added support for PostCSS 8.

### CODE REVIEW

**Comment by simonsmith** [comment]
Nice!

**Review by simonsmith — APPROVED** [review]

**Comment by niksy** [comment]
Safe to publish new major version?

**Comment by simonsmith** [comment]
Yup, do you have npm access?

**Comment by niksy** [comment]
@simonsmith nope!

**Comment by simonsmith** [comment]
What's your username and I'll add you :)

**Comment by niksy** [comment]
niksy

**Comment by simonsmith** [comment]
Done, let me know if any issues

**Comment by niksy** [comment]
All good!

**Pull request merged**
